FLIP_IMAGE = True
WINDOW_NAME = "Light Drawing"
NUM_ROUNDS = 2
COUNTDOWN_DURATION = 3
ROUND_DURATION = 5
POST_ROUND_DURATION = 5

WORLD_SPACE_WIDTH = 500
WORLD_SPACE_WIDTH = 500

WORLD_SPACE_SIZE = (WORLD_SPACE_WIDTH, WORLD_SPACE_WIDTH)
